random_seed: 32

model:
  name: "VGG19"
  weights: "imagenet"
  include_top: false
  use_pretrained: true

image:
  size: [224, 224, 3]

training:
  batch_size: 16
  epochs: 100
  dropout_rate: 0.5
  loss: "sparse_categorical_crossentropy"
  metrics: ["accuracy"]


optimizer:
  name: Adam()
  learning_rate: 0.001
  beta_1: 0.9
  beta_2: 0.999
  epsilon: 1e-07
  momentum: 0.9
  nesterov: true
  rho: 0.9

augmentation:
  enabled: true
  horizontal_flip: true
  rotation_factor: 0.05
  zoom_factor: 0.05
  # Advanced parameters (will be loaded if present)
  rotation_range: 20  # graus
  brightness_range: [0.8, 1.2]  # [min, max]
  zoom_range: [0.9, 1.1]  # [min, max]
  contrast_range: [0.9, 1.1]  # [min, max]
  gaussian_noise: 0.02  # fator de ruído
dataset:
  classes: 3
  train_ratio: 0.8
  val_ratio: 0.2
  
# Diferentes configurações para experimentação
experiments:
  mobilenet:
    model:
      name: "MobileNetV3"
      use_pretrained: true
      weights: "imagenet"
      include_top: false
      dropout_rate: 0.3


    augmentation:
      # Inspirado no paper YOLOv5 - adaptado para classificação
      advanced_enabled: true
      mosaic_probability: 0.5  # Mosaic adaptado para classificação
      mixup_probability: 0.15  # MixUp (suportado nativamente)
      cutmix_probability: 0.25  # CutMix para melhor generalização
      
      healthy_specific:
        # Aumentado baseado no paper (backgrounds múltiplos)
        rotation_range: 45  # Aumentado de 30
        horizontal_flip: true
        vertical_flip: true
        brightness_range: [0.6, 1.4]  # Range maior como no paper
        zoom_range: [0.7, 1.3]  # Range maior
        shear_range: 0.2  # Aumentado
        fill_mode: "nearest"
        target_samples: 500
        # Novas técnicas do paper
        gaussian_noise: 0.05
        contrast_range: [0.8, 1.2]
        saturation_range: [0.8, 1.2]
        multiple_backgrounds: true  # Simular diferentes backgrounds
        edge_enhancement: true
      
      general:
        rotation_range: 20  # Aumentado de 15
        horizontal_flip: true
        brightness_range: [0.8, 1.2]  # Range maior
        zoom_range: [0.9, 1.1]
        # Adicionais baseadas no paper
        gaussian_noise: 0.02
        contrast_range: [0.9, 1.1]

    training:
      epochs: 100
      batch_size: 16
      class_weights:
        0: 0.7    # Caterpillar (638 amostras)
        1: 1.0    # Diabrotica (468 amostras)
        2: 2.5    # Healthy (176 amostras) - PESO MAIOR
  vgg_transfer:
    model:
      name: "VGG19"
      use_pretrained: true
      weights: "imagenet"
      include_top: false

      # dropout_rate: 0.0
    training:
      epochs: 100
      batch_size: 16
      class_weights:
        0: 1.0    # Caterpillar (638 amostras)
        1: 1.0    # Diabrotica (468 amostras)
        2: 2.5    # Healthy (176 amostras) - PESO MAIOR